import { cellToText } from './cell-to-text'

it('identifies the basic letters', () => {
    expect(cellToText('⠁')).toEqual('a')
    expect(cellToText('⠃')).toEqual('b')
    expect(cellToText('⠉')).toEqual('c')
    expect(cellToText('⠙')).toEqual('d')
    expect(cellToText('⠑')).toEqual('e')
    expect(cellToText('⠋')).toEqual('f')
    expect(cellToText('⠛')).toEqual('g')
    expect(cellToText('⠓')).toEqual('h')
    expect(cellToText('⠊')).toEqual('i')
    expect(cellToText('⠚')).toEqual('j')
    expect(cellToText('⠅')).toEqual('k')
    expect(cellToText('⠇')).toEqual('l')
    expect(cellToText('⠍')).toEqual('m')
    expect(cellToText('⠝')).toEqual('n')
    expect(cellToText('⠕')).toEqual('o')
    expect(cellToText('⠏')).toEqual('p')
    expect(cellToText('⠟')).toEqual('q')
    expect(cellToText('⠗')).toEqual('r')
    expect(cellToText('⠎')).toEqual('s')
    expect(cellToText('⠞')).toEqual('t')
    expect(cellToText('⠥')).toEqual('u')
    expect(cellToText('⠧')).toEqual('v')
    expect(cellToText('⠺')).toEqual('w')
    expect(cellToText('⠭')).toEqual('x')
    expect(cellToText('⠽')).toEqual('y')
    expect(cellToText('⠵')).toEqual('z')
})
